CREATE TABLE Role
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(12) UNIQUE NOT NULL
        CHECK (role_name IN ('USER', 'ADMIN', 'SUPER_ADMIN'))
);

INSERT INTO Role (role_name)
VALUES ('USER'),
       ('ADMIN'),
       ('SUPER_ADMIN');

CREATE TABLE USER_ROLE
(
    user_id INT REFERENCES Users,
    role_id INT REFERENCES Role,
    CONSTRAINT user_role_pk PRIMARY KEY (user_id, role_id)
);
